#!/bin/sh
set -e

. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
  purge)
    # Activate trigger to rebuild workbench configuration files.
    dpkg-trigger update-workbench
    omv_config_delete "/config/system/sleepproxyclient"
    ;;
  remove|upgrade|failed-upgrade)
    dpkg-trigger update-workbench
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "postrm called with unknown argument '$1'" >&2
    exit 1
    ;;

esac

#DEBHELPER#
exit 0
